language: node_js
env: 
  global: 
  - secure: "iiAWfVJ90ogzcgl46acbQYzVth25a0++87OlXbV0/fR6gkRU535FcLb8jIoFpOdDMAwyXWw/qlZkxJKknrXW7vPRrYmQo3ijsAbV23piv71eOtOXzd9Slhqq4feXnYAUdZ/f/5hcW4t1ws1Dbmhd9Iie5jqT6FWIShmYBCEpnqc="
  - GH_OWNER: lmorchard
  - GH_PROJECT_NAME: parsec-patrol
node_js: 
- 0.8
branches: 
  only: 
  - master
before_script: 
- npm install -g grunt-cli bower
after_success: 
- git submodule add -b gh-pages https://${GH_OAUTH_TOKEN}@github.com/${GH_OWNER}/${GH_PROJECT_NAME} site > /dev/null 2>&1
- cd site
- node ../app/scripts/util/cleanup.js ../dist/index.html
- if git checkout gh-pages; then git checkout -b gh-pages; fi
- git rm -r .
- cp -R ../dist/* .
- cp ../dist/.* .
- git add -f .
- git config user.email "me@lmorchard.com"
- git config user.name "Les Orchard"
- git commit -am "adding the yeoman build files to gh-pages"
- git push https://${GH_OAUTH_TOKEN}@github.com/${GH_OWNER}/${GH_PROJECT_NAME} HEAD:gh-pages > /dev/null 2>&1
script: 
- npm install
- bower install
- grunt
